test

diff --git a/.github/workflows/tidy-clang.yml b/.github/workflows/tidy-clang.yml
--- a/.github/workflows/tidy-clang.yml
+++ b/.github/workflows/tidy-clang.yml
@@ -26,19 +26,29 @@ jobs:
           # Full git history is needed to get a proper list of changed files within `super-linter`
           fetch-depth: 0
 
-      - uses: cpp-linter/cpp-linter-action@v2
-        id: linter
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          style: ''  # Use .clang-format config file
-          tidy-checks: '' # Use .clang-tidy config file
-          extra-args: '-std=c++17'
-          verbosity: debug
-          tidy-review: true
-          passive-reviews: true
+      - uses: ZedThree/clang-tidy-review@v0.14.0
+        id: review
+
+      # Uploads an artefact containing clang_fixes.json
+      - uses: ZedThree/clang-tidy-review/upload@v0.14.0
+        id: upload-review
+
+      # If there are any comments, fail the check
+      - if: steps.review.outputs.total_comments > 0
+        run: exit 1
+      #- uses: cpp-linter/cpp-linter-action@v2
+       # id: linter
+       # env:
+       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+       # with:
+       #   style: ''  # Use .clang-format config file
+       #   tidy-checks: '' # Use .clang-tidy config file
+       #   extra-args: '-std=c++17'
+       #   verbosity: debug
+       #   tidy-review: true
+       #   passive-reviews: true
           # only 'update' a single comment in a pull request thread.
           #thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
-      - name: Fail fast?!
-        if: steps.linter.outputs.checks-failed > 0
-        run: exit 1
+      #- name: Fail fast?!
+      #  if: steps.linter.outputs.checks-failed > 0
+      #  run: exit 1
